site_name: ENTWICKLERPROGRAMM
site_author: Shane White
repo_url: https://github.com/Entwicklerprogramm/main/
theme: readthedocs

pages:
  - Introduction: 'index.md'
  - Configuration: 'config.md'
  - Raspberry Pi: 'rpi.md'
  - About: 'about.md'

